import { Brand, Product, CarouselSlide, DiscountCode, Device } from './types';

export const INITIAL_PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'iPhone 15 Pro Max Case - Midnight',
        price: 25000,
        description: 'Premium silicone case with MagSafe support. Soft-touch finish and microfiber lining.',
        category: 'Cases',
        image: 'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=800&q=80'],
        brand: 'Apple',
        device: 'iPhone 15 Pro Max',
        stock: 50,
        rating: 4.8,
        colors: ['#000000', '#1a1a1a'],
        variants: [],
        sku: 'IP15PM-MID'
    },
    {
        id: '2',
        name: 'Samsung S24 Ultra Clear Case',
        price: 20000,
        description: 'Crystal clear protection that resists yellowing. Reinforced corners for drop protection.',
        category: 'Cases',
        image: 'https://images.unsplash.com/photo-1610945265078-3858a0828671?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1610945265078-3858a0828671?auto=format&fit=crop&w=800&q=80'],
        brand: 'Samsung',
        device: 'Samsung S24 Ultra',
        stock: 35,
        rating: 4.5,
        colors: ['#ffffff'],
        variants: [],
        sku: 'S24U-CLR'
    }
];

export const INITIAL_BRANDS: Brand[] = [
    { id: '1', name: 'Apple', logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg' },
    { id: '2', name: 'Samsung', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg' },
    { id: '3', name: 'Google', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg' },
    { id: '4', name: 'Xiaomi', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Xiaomi_logo_%282021-%29.svg' },
    { id: '5', name: 'Huawei', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Huawei_Logo.svg' }
];

export const INITIAL_SLIDES: CarouselSlide[] = [
    {
        id: '1',
        image: 'https://images.unsplash.com/photo-1603351154351-5cfb3d04ef32?auto=format&fit=crop&w=1600&q=80',
        title: 'New Collection',
        link: '/search?q=new'
    },
    {
        id: '2',
        image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=1600&q=80',
        title: 'Best Sellers',
        link: '/search?q=best'
    }
];

export const DEVICES: Device[] = [
    { id: '1', name: 'iPhone 15 Pro Max' },
    { id: '2', name: 'iPhone 15 Pro' },
    { id: '3', name: 'iPhone 15' },
    { id: '4', name: 'Samsung S24 Ultra' },
    { id: '5', name: 'Samsung S24 Plus' },
    { id: '6', name: 'Samsung S24' },
    { id: '7', name: 'Pixel 8 Pro' },
    { id: '8', name: 'Pixel 8' }
];

export const TRANSLATIONS = {
    en: {
        home: 'Home',
        search: 'Search',
        cart: 'Cart',
        checkout: 'Checkout',
        addToCart: 'Add to Cart',
        buyNow: 'Buy Now',
        description: 'Description',
        relatedProducts: 'Related Products',
        reviews: 'Reviews',
        outOfStock: 'Out of Stock',
        selectColor: 'Select Color',
        selectDevice: 'Select Device',
        total: 'Total',
        subtotal: 'Subtotal',
        shipping: 'Shipping',
        free: 'Free',
        placeOrder: 'Place Order',
        success: 'Success',
        error: 'Error',
        login: 'Login',
        logout: 'Logout',
        admin: 'Admin',
        settings: 'Settings',
        products: 'Products',
        brands: 'Brands',
        orders: 'Orders',
        dashboard: 'Dashboard',
        bestSellers: 'Best Sellers',
        latestDrops: 'Latest Drops',
        popular: 'Popular',
        viewAll: 'View All',
        loading: 'Loading...',
        noProducts: 'No products found',
        tryAgain: 'Try Again',
        apply: 'Apply',
        discountCode: 'Discount Code',
        remove: 'Remove',
        update: 'Update',
        cancel: 'Cancel',
        save: 'Save',
        delete: 'Delete',
        edit: 'Edit',
        new: 'New',
        all: 'All',
        filter: 'Filter',
        sort: 'Sort',
        priceHighToLow: 'Price: High to Low',
        priceLowToHigh: 'Price: Low to High',
        newest: 'Newest',
        nameAZ: 'Name: A-Z',
        nameZA: 'Name: Z-A',
        searchPlaceholder: 'Search for products...',
        orderConfirmed: 'Order Confirmed',
        thankYou: 'Thank you for your order!',
        orderId: 'Order ID',
        continueShopping: 'Continue Shopping',
        emptyCart: 'Your cart is empty',
        startShopping: 'Start Shopping',
        itemAdded: 'Item added to cart',
        itemRemoved: 'Item removed from cart',
        quantityUpdated: 'Quantity updated',
        wishlist: 'Wishlist',
        addToWishlist: 'Add to Wishlist',
        removeFromWishlist: 'Remove from Wishlist',
        contactUs: 'Contact Us',
        aboutUs: 'About Us',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        maintenance: 'Maintenance',
        databaseSetup: 'Database Setup',
        runScript: 'Run Script',
        scriptCopied: 'Script copied to clipboard',
        notification: 'Notification',
        notificationMessage: 'Notification Message',
        updateNotification: 'Update Notification',
        notificationUpdated: 'Notification updated successfully',
        theme: 'Theme',
        language: 'Language',
        light: 'Light',
        dark: 'Dark',
        english: 'English',
        arabic: 'Arabic',
        hurryOnly: 'Hurry! Only',
        leftInStock: 'left in stock',
        youMightAlsoLike: 'You Might Also Like',
        genericProductDesc: 'This product is made with high quality materials and designed to last.',
        fastShipping: 'Fast Shipping',
        fastShippingDesc: 'Get your order delivered within 24 hours.',
        qualityGuarantee: 'Quality Guarantee',
        qualityDesc: 'We ensure the best quality for all our products.',
        inStock: 'In Stock'
    },
    ar: {
        home: 'الرئيسية',
        search: 'بحث',
        cart: 'السلة',
        checkout: 'الدفع',
        addToCart: 'أضف للسلة',
        buyNow: 'اشتر الآن',
        description: 'الوصف',
        relatedProducts: 'منتجات ذات صلة',
        reviews: 'المراجعات',
        outOfStock: 'نفذت الكمية',
        selectColor: 'اختر اللون',
        selectDevice: 'اختر الجهاز',
        total: 'المجموع',
        subtotal: 'المجموع الفرعي',
        shipping: 'الشحن',
        free: 'مجاني',
        placeOrder: 'تأكيد الطلب',
        success: 'نجاح',
        error: 'خطأ',
        login: 'دخول',
        logout: 'خروج',
        admin: 'مسؤول',
        settings: 'الإعدادات',
        products: 'المنتجات',
        brands: 'الماركات',
        orders: 'الطلبات',
        dashboard: 'لوحة التحكم',
        bestSellers: 'الأكثر مبيعاً',
        latestDrops: 'أحدث المنتجات',
        popular: 'شائع',
        viewAll: 'عرض الكل',
        loading: 'جاري التحميل...',
        noProducts: 'لا توجد منتجات',
        tryAgain: 'حاول مرة أخرى',
        apply: 'تطبيق',
        discountCode: 'كود الخصم',
        remove: 'إزالة',
        update: 'تحديث',
        cancel: 'إلغاء',
        save: 'حفظ',
        delete: 'حذف',
        edit: 'تعديل',
        new: 'جديد',
        all: 'الكل',
        filter: 'تصفية',
        sort: 'ترتيب',
        priceHighToLow: 'السعر: من الأعلى للأقل',
        priceLowToHigh: 'السعر: من الأقل للأعلى',
        newest: 'الأحدث',
        nameAZ: 'الاسم: أ-ي',
        nameZA: 'الاسم: ي-أ',
        searchPlaceholder: 'ابحث عن منتجات...',
        orderConfirmed: 'تم تأكيد الطلب',
        thankYou: 'شكراً لطلبك!',
        orderId: 'رقم الطلب',
        continueShopping: 'متابعة التسوق',
        emptyCart: 'سلتك فارغة',
        startShopping: 'ابدأ التسوق',
        itemAdded: 'تمت إضافة المنتج للسلة',
        itemRemoved: 'تمت إزالة المنتج من السلة',
        quantityUpdated: 'تم تحديث الكمية',
        wishlist: 'المفضلة',
        addToWishlist: 'أضف للمفضلة',
        removeFromWishlist: 'إزالة من المفضلة',
        contactUs: 'اتصل بنا',
        aboutUs: 'من نحن',
        privacyPolicy: 'سياسة الخصوصية',
        termsOfService: 'شروط الخدمة',
        maintenance: 'الصيانة',
        databaseSetup: 'إعداد قاعدة البيانات',
        runScript: 'تشغيل السكربت',
        scriptCopied: 'تم نسخ السكربت',
        notification: 'إشعار',
        notificationMessage: 'رسالة الإشعار',
        updateNotification: 'تحديث الإشعار',
        notificationUpdated: 'تم تحديث الإشعار بنجاح',
        theme: 'المظهر',
        language: 'اللغة',
        light: 'فاتح',
        dark: 'داكن',
        english: 'إنجليزي',
        arabic: 'عربي',
        hurryOnly: 'سارع! تبقى',
        leftInStock: 'فقط في المخزون',
        youMightAlsoLike: 'قد يعجبك أيضاً',
        genericProductDesc: 'هذا المنتج مصنوع من مواد عالية الجودة ومصمم ليدوم طويلاً.',
        fastShipping: 'شحن سريع',
        fastShippingDesc: 'احصل على طلبك خلال 24 ساعة.',
        qualityGuarantee: 'ضمان الجودة',
        qualityDesc: 'نحن نضمن أفضل جودة لجميع منتجاتنا.',
        inStock: 'متوفر'
    }
};

export const INITIAL_DISCOUNTS: DiscountCode[] = [
    { id: '1', code: 'WELCOME10', type: 'percentage', value: 10, minOrderAmount: 0, isActive: true },
    { id: '2', code: 'FREESHIP', type: 'fixed', value: 5000, minOrderAmount: 50000, isActive: true }
];

export const INITIAL_ORDERS: any[] = [];
