import { Brand, Product, CarouselSlide, DiscountCode, Device } from './types';

export const INITIAL_PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'iPhone 15 Pro Max Case - Midnight',
        price: 25000,
        description: 'Premium silicone case with MagSafe support. Soft-touch finish and microfiber lining.',
        category: 'Cases',
        image: 'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=800&q=80'],
        brand: 'Apple',
        device: 'iPhone 15 Pro Max',
        stock: 50,
        rating: 4.8,
        colors: ['#000000', '#1a1a1a'],
        variants: [],
        sku: 'IP15PM-MID'
    },
    {
        id: '2',
        name: 'Samsung S24 Ultra Clear Case',
        price: 20000,
        description: 'Crystal clear protection that resists yellowing. Reinforced corners for drop protection.',
        category: 'Cases',
        image: 'https://images.unsplash.com/photo-1610945265078-3858a0828671?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1610945265078-3858a0828671?auto=format&fit=crop&w=800&q=80'],
        brand: 'Samsung',
        device: 'Samsung S24 Ultra',
        stock: 35,
        rating: 4.5,
        colors: ['#ffffff'],
        variants: [],
        sku: 'S24U-CLR'
    }
];

export const INITIAL_BRANDS: Brand[] = [
    { id: '1', name: 'Apple', logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg' },
    { id: '2', name: 'Samsung', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg' },
    { id: '3', name: 'Google', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg' },
    { id: '4', name: 'Xiaomi', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Xiaomi_logo_%282021-%29.svg' },
    { id: '5', name: 'Huawei', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Huawei_Logo.svg' }
];

export const INITIAL_SLIDES: CarouselSlide[] = [
    {
        id: '1',
        image: 'https://images.unsplash.com/photo-1603351154351-5cfb3d04ef32?auto=format&fit=crop&w=1600&q=80',
        title: 'New Collection',
        link: '/search?q=new'
    },
    {
        id: '2',
        image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=1600&q=80',
        title: 'Best Sellers',
        link: '/search?q=best'
    }
];

export const DEVICES: Device[] = [
    { id: '1', name: 'iPhone 15 Pro Max' },
    { id: '2', name: 'iPhone 15 Pro' },
    { id: '3', name: 'iPhone 15' },
    { id: '4', name: 'Samsung S24 Ultra' },
    { id: '5', name: 'Samsung S24 Plus' },
    { id: '6', name: 'Samsung S24' },
    { id: '7', name: 'Pixel 8 Pro' },
    { id: '8', name: 'Pixel 8' }
];

export const TRANSLATIONS = {
    en: {
        home: 'Home',
        back: 'Back',
        search: 'Search',
        cart: 'Cart',
        checkout: 'Checkout',
        addToCart: 'Add to Cart',
        buyNow: 'Buy Now',
        description: 'Description',
        relatedProducts: 'Related Products',
        reviews: 'Reviews',
        outOfStock: 'Out of Stock',
        selectColor: 'Select Color',
        selectDevice: 'Select Device',
        total: 'Total',
        subtotal: 'Subtotal',
        shipping: 'Shipping',
        free: 'Free',
        placeOrder: 'Place Order',
        success: 'Success',
        error: 'Error',
        login: 'Login',
        logout: 'Logout',
        admin: 'Admin',
        settings: 'Settings',
        products: 'Products',
        brands: 'Brands',
        orders: 'Orders',
        dashboard: 'Dashboard',
        bestSellers: 'Best Sellers',
        latestDrops: 'Latest Drops',
        popular: 'Popular',
        viewAll: 'View All',
        loading: 'Loading...',
        noProducts: 'No products found',
        tryAgain: 'Try Again',
        apply: 'Apply',
        discount: 'Discount',
        discountCode: 'Discount Code',
        remove: 'Remove',
        update: 'Update',
        cancel: 'Cancel',
        save: 'Save',
        delete: 'Delete',
        edit: 'Edit',
        new: 'New',
        all: 'All',
        filter: 'Filter',
        sort: 'Sort',
        priceHighToLow: 'Price: High to Low',
        priceLowToHigh: 'Price: Low to High',
        newest: 'Newest',
        nameAZ: 'Name: A-Z',
        nameZA: 'Name: Z-A',
        searchPlaceholder: 'Search for products...',
        orderConfirmed: 'Order Confirmed',
        thankYou: 'Thank you for your order!',
        orderId: 'Order ID',
        continueShopping: 'Continue Shopping',
        emptyCart: 'Your cart is empty',
        startShopping: 'Start Shopping',
        itemAdded: 'Item added to cart',
        itemRemoved: 'Item removed from cart',
        quantityUpdated: 'Quantity updated',
        wishlist: 'Wishlist',
        addToWishlist: 'Add to Wishlist',
        removeFromWishlist: 'Remove from Wishlist',
        contactUs: 'Contact Us',
        aboutUs: 'About Us',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        maintenance: 'Maintenance',
        databaseSetup: 'Database Setup',
        runScript: 'Run Script',
        scriptCopied: 'Script copied to clipboard',
        notification: 'Notification',
        notificationMessage: 'Notification Message',
        updateNotification: 'Update Notification',
        notificationUpdated: 'Notification updated successfully',
        theme: 'Theme',
        language: 'Language',
        light: 'Light',
        dark: 'Dark',
        english: 'English',
        arabic: 'Arabic',
        hurryOnly: 'Hurry! Only',
        leftInStock: 'left in stock',
        youMightAlsoLike: 'You Might Also Like',
        genericProductDesc: '',
        fastShipping: 'Fast Shipping',
        fastShippingDesc: 'Get your order delivered within 24 hours.',
        qualityGuarantee: 'Quality Guarantee',
        qualityDesc: 'We ensure the best quality for all our products.',
        inStock: 'In Stock',
        completeOrder: 'Complete Order',
        fullName: 'Full Name',
        phone: 'Phone Number',
        governorate: 'Governorate',
        selectGovernorate: 'Select Governorate',
        address: 'Address',
        deliveryDetails: 'Delivery Details',
        secureCheckout: 'Secure Checkout',
        orderSummary: 'Order Summary',
        qty: 'Qty',
        checkoutTitle: 'Checkout',
        cashOnDelivery: 'Cash on Delivery',
        baghdad: 'Baghdad',
        basra: 'Basra',
        nineveh: 'Nineveh',
        erbil: 'Erbil',
        duhok: 'Duhok',
        sulaymaniyah: 'Sulaymaniyah',
        kirkuk: 'Kirkuk',
        diyala: 'Diyala',
        anbar: 'Anbar',
        babil: 'Babil',
        karbala: 'Karbala',
        najaf: 'Najaf',
        qadisiyah: 'Al-Qadisiyah',
        muthanna: 'Al-Muthanna',
        wasit: 'Wasit',
        maysan: 'Maysan',
        saladin: 'Saladin',
        halabja: 'Halabja',
        diwaniya: 'Al-Diwaniyah',
        received: 'received',
        importantInfo: 'Important Information',
        estimatedDelivery: 'Estimated Delivery',
        reachYouIn: 'Your order should reach you in',
        hours: 'hours',
        uponDelivery: 'Upon Delivery',
        checkOrder: 'Please check your order',
        beforePaying: 'before paying',
        processing: 'Processing',
        shipped: 'Shipped',
        delivered: 'Delivered',
        myOrders: 'My Orders',
        trackOrdersSubtitle: 'Track your orders by phone number',
        searchingOrders: 'Searching for your orders...',
        trackBtn: 'Track',
        noOrdersFound: 'No orders found',
        tryCheckingPhone: 'Try checking with a different phone number',
        orderNum: 'Order #',
        items: 'items',
        forDevice: 'for',
        fullDetails: 'Full Details',
        results: 'results',
        noMatches: 'No matches found',
        popularSearches: 'Popular Searches',
        noDeviceMatch: 'No products found for this device',

        aiIntro: "Hello! I'm {name}, your personal shopping assistant. How can I help you today?",
        askStyles: "Ask about styles, products, or compatibility...",
        alwaysHelp: "I'm here to help you find the perfect accessory!",
        verifiedReviews: 'Verified Reviews',
        writeReview: 'Write a Review',
        rating: 'Rating',
        name: 'Name',
        enterName: 'Enter your name',
        comment: 'Comment',
        shareExperience: 'Share your experience...',
        submitReview: 'Submit Review',
        noReviewsYet: 'No reviews yet. Be the first to review!',
        linkCopied: 'Link copied to clipboard',
        errorCopying: 'Error copying link',
        adminDashboard: 'Admin Dashboard',
        online: 'Online',
        offline: 'Offline',
        exit: 'Exit',
        myWishlist: 'My Wishlist',
        status: 'Status',
        demoMode: 'Demo Mode'
    },
    ar: {

        home: 'الرئيسية',
        back: 'رجوع',
        search: 'بحث',
        cart: 'السلة',
        checkout: 'اكمال الطلب',
        addToCart: 'أضف للسلة',
        buyNow: 'اشتر الآن',
        description: 'الوصف',
        relatedProducts: 'منتجات ذات صلة',
        reviews: 'المراجعات',
        outOfStock: 'نفذت الكمية',
        selectColor: 'اختر اللون',
        selectDevice: 'اختر الجهاز',
        total: 'المجموع',
        subtotal: 'سعر المنتجات',
        shipping: 'الشحن',
        free: 'مجاني',
        placeOrder: 'تأكيد الطلب',
        success: 'نجاح',
        error: 'خطأ',
        login: 'دخول',
        logout: 'خروج',
        admin: 'مسؤول',
        settings: 'الإعدادات',
        products: 'المنتجات',
        brands: 'الماركات',
        orders: 'الطلبات',
        dashboard: 'لوحة التحكم',
        bestSellers: 'الأكثر مبيعاً',
        latestDrops: 'أحدث المنتجات',
        popular: 'شائع',
        viewAll: 'عرض الكل',
        loading: 'جاري التحميل...',
        noProducts: 'لا توجد منتجات',
        tryAgain: 'حاول مرة أخرى',
        apply: 'تطبيق',
        discount: 'خصم',
        discountCode: 'كود الخصم',
        remove: 'إزالة',
        update: 'تحديث',
        cancel: 'إلغاء',
        save: 'حفظ',
        delete: 'حذف',
        edit: 'تعديل',
        new: 'جديد',
        all: 'الكل',
        filter: 'تصفية',
        sort: 'ترتيب',
        priceHighToLow: 'السعر: من الأعلى للأقل',
        priceLowToHigh: 'السعر: من الأقل للأعلى',
        newest: 'الأحدث',
        nameAZ: 'الاسم: أ-ي',
        nameZA: 'الاسم: ي-أ',
        searchPlaceholder: 'ابحث عن منتجات...',
        orderConfirmed: 'تم تأكيد الطلب',
        thankYou: 'شكراً لطلبك!',
        orderId: 'رقم الطلب',
        continueShopping: 'متابعة التسوق',
        emptyCart: 'سلتك فارغة',
        startShopping: 'ابدأ التسوق',
        itemAdded: 'تمت إضافة المنتج للسلة',
        itemRemoved: 'تمت إزالة المنتج من السلة',
        quantityUpdated: 'تم تحديث الكمية',
        wishlist: 'المفضلة',
        addToWishlist: 'أضف للمفضلة',
        removeFromWishlist: 'إزالة من المفضلة',
        contactUs: 'اتصل بنا',
        aboutUs: 'من نحن',
        privacyPolicy: 'سياسة الخصوصية',
        termsOfService: 'شروط الخدمة',
        maintenance: 'الصيانة',
        databaseSetup: 'إعداد قاعدة البيانات',
        runScript: 'تشغيل السكربت',
        scriptCopied: 'تم نسخ السكربت',
        notification: 'إشعار',
        notificationMessage: 'رسالة الإشعار',
        updateNotification: 'تحديث الإشعار',
        notificationUpdated: 'تم تحديث الإشعار بنجاح',
        theme: 'المظهر',
        language: 'اللغة',
        light: 'فاتح',
        dark: 'داكن',
        english: 'إنجليزي',
        arabic: 'عربي',
        hurryOnly: 'سارع! تبقى',
        leftInStock: 'فقط في المخزون',
        youMightAlsoLike: 'قد يعجبك أيضاً',
        genericProductDesc: '',
        fastShipping: 'شحن سريع',
        fastShippingDesc: 'احصل على طلبك خلال 24 ساعة.',
        qualityGuarantee: 'ضمان الجودة',
        qualityDesc: 'نحن نضمن أفضل جودة لجميع منتجاتنا.',
        inStock: 'متوفر',
        completeOrder: 'إتمام الطلب',
        fullName: 'الاسم الكامل',
        phone: 'رقم الهاتف',
        governorate: 'المحافظة',
        selectGovernorate: 'اختر المحافظة',
        address: 'العنوان',
        deliveryDetails: 'تفاصيل التوصيل',
        secureCheckout: 'دفع آمن',
        orderSummary: 'ملخص الطلب',
        qty: 'الكمية',
        checkoutTitle: 'الدفع',
        cashOnDelivery: 'الدفع عند الاستلام',
        baghdad: 'بغداد',
        basra: 'البصرة',
        nineveh: 'نينوى',
        erbil: 'أربيل',
        duhok: 'دهوك',
        sulaymaniyah: 'السليمانية',
        kirkuk: 'كركوك',
        diyala: 'ديالى',
        anbar: 'الأنبار',
        babil: 'بابل',
        karbala: 'كربلاء',
        najaf: 'النجف',
        qadisiyah: 'القادسية',
        muthanna: 'المثنى',
        wasit: 'واسط',
        maysan: 'ميسان',
        saladin: 'صلاح الدين',
        halabja: 'حلبجة',
        diwaniya: 'الديوانية',
        received: 'استلمنا',
        importantInfo: 'معلومات مهمة',
        estimatedDelivery: 'وقت التوصيل المتوقع',
        reachYouIn: 'سيصلك طلبك خلال',
        hours: 'ساعة',
        uponDelivery: 'عند الاستلام',
        checkOrder: 'يرجى التحقق من طلبك',
        beforePaying: 'قبل الدفع',
        processing: 'قيد المعالجة',
        shipped: 'تم الشحن',
        delivered: 'تم التوصيل',
        myOrders: 'طلباتي',
        trackOrdersSubtitle: 'تتبع طلباتك برقم الهاتف',
        searchingOrders: 'جاري البحث عن طلباتك...',
        trackBtn: 'تتبع',
        noOrdersFound: 'لم يتم العثور على طلبات',
        tryCheckingPhone: 'حاول التحقق برقم هاتف آخر',
        orderNum: 'طلب رقم #',
        items: 'قطع',
        forDevice: 'لجهاز',
        fullDetails: 'التفاصيل الكاملة',
        results: 'نتائج',
        noMatches: 'لم يتم العثور على نتائج',
        popularSearches: 'عمليات البحث الشائعة',
        noDeviceMatch: 'لم يتم العثور على منتجات لهذا الجهاز',

        aiIntro: "مرحباً! أنا {name}، مساعدتك الشخصية للتسوق. كيف يمكنني مساعدتك اليوم؟",
        askStyles: "اسأل عن الموديلات، المنتجات، أو التوافق...",
        alwaysHelp: "أنا هنا لمساعدتك في العثور على الإكسسوار المثالي!",
        verifiedReviews: 'مراجعات موثقة',
        writeReview: 'اكتب مراجعة',
        rating: 'التقييم',
        name: 'الاسم',
        enterName: 'أدخل اسمك',
        comment: 'التعليق',
        shareExperience: 'شارك تجربتك...',
        submitReview: 'إرسال المراجعة',
        noReviewsYet: 'لا توجد مراجعات بعد. كن أول من يقيم!',
        linkCopied: 'تم نسخ الرابط',
        errorCopying: 'خطأ في نسخ الرابط',
        adminDashboard: 'لوحة المسؤول',
        online: 'متصل',
        offline: 'غير متصل',
        exit: 'خروج',
        myWishlist: 'قائمة رغباتي',
        status: 'الحالة',
        demoMode: 'الوضع التجريبي'
    }
};

export const INITIAL_DISCOUNTS: DiscountCode[] = [
    { id: '1', code: 'WELCOME10', type: 'percentage', value: 10, minOrderAmount: 0, isActive: true },
    { id: '2', code: 'FREESHIP', type: 'fixed', value: 5000, minOrderAmount: 50000, isActive: true }
];

export const IRAQI_GOVERNORATES = [
    { value: 'Baghdad', labelKey: 'baghdad' },
    { value: 'Basra', labelKey: 'basra' },
    { value: 'Nineveh', labelKey: 'nineveh' },
    { value: 'Erbil', labelKey: 'erbil' },
    { value: 'Duhok', labelKey: 'duhok' },
    { value: 'Sulaymaniyah', labelKey: 'sulaymaniyah' },
    { value: 'Kirkuk', labelKey: 'kirkuk' },
    { value: 'Diyala', labelKey: 'diyala' },
    { value: 'Anbar', labelKey: 'anbar' },
    { value: 'Babil', labelKey: 'babil' },
    { value: 'Karbala', labelKey: 'karbala' },
    { value: 'Najaf', labelKey: 'najaf' },
    { value: 'Qadisiyah', labelKey: 'qadisiyah' },
    { value: 'Muthanna', labelKey: 'muthanna' },
    { value: 'Wasit', labelKey: 'wasit' },
    { value: 'Maysan', labelKey: 'maysan' },
    { value: 'Saladin', labelKey: 'saladin' },
    { value: 'Halabja', labelKey: 'halabja' },
    { value: 'Diwaniya', labelKey: 'diwaniya' }
];

export const EMAILJS_CONFIG = {
    SERVICE_ID: import.meta.env.VITE_EMAILJS_SERVICE_ID || 'service_1aqnoan',
    TEMPLATE_ID: import.meta.env.VITE_EMAILJS_TEMPLATE_ID || 'template_l5a9ibb',
    PUBLIC_KEY: import.meta.env.VITE_EMAILJS_PUBLIC_KEY || 't87f32aAOSQ9bpd22',
    TARGET_EMAIL: import.meta.env.VITE_EMAILJS_TARGET_EMAIL || 'mostmaz73@gmail.com, sifyanalkhafaf1@gmail.com'
};

export const TWILIO_CONFIG = {
    ACCOUNT_SID: import.meta.env.VITE_TWILIO_ACCOUNT_SID || 'YOUR_TWILIO_ACCOUNT_SID',
    AUTH_TOKEN: import.meta.env.VITE_TWILIO_AUTH_TOKEN || 'YOUR_TWILIO_AUTH_TOKEN',
    FROM_NUMBER: import.meta.env.VITE_TWILIO_FROM_NUMBER || 'whatsapp:+14155238886',
    ADMIN_NUMBER: import.meta.env.VITE_TWILIO_ADMIN_NUMBER || '+9647502062804'
};

export const INITIAL_ORDERS: any[] = [];

export const ENCODED_PIN = 'MTUwODkzNDEyQ0Bj'; // Encoded PIN for 150893412C@c
